#!/usr/bin/env bash
# pth=`pwd`

if [[ $# == 1 ]]; then
    filen=`basename $1`
    build/taxonoviz -i $1 $1.dot
    fdp -Tpng $1.dot -o $1.png
elif [[ $# == 2 ]]; then
    filen=`basename $1`
    build/taxonoviz -i $1 -o $2/$filen.dot
    fdp -Tpng $2/$filen.dot -o $2/$filen.png
else
    echo "Usage: ./taxo <taxonomy.ow> [path/to/output/directory]"
fi